secrets:
  nextcloud_admin-password:
    external: true
  nextcloud_admin-user:
    external: true
  portainer_admin-password:
    external: true

services:
  adminer:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.middlewares=redirectscheme
      - traefik.http.routers.adminer.rule=Host(`adminer.mcleut.stack`)
      - traefik.http.routers.adminer_secure.rule=Host(`adminer.mcleut.stack`)
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer_secure.tls.options=mintls13@file
      placement:
        constraints:
        - node.role == manager
    image: adminer:latest
#    volumes:
#    - /production/adminer_data/adminer.css:/var/www/html/adminer.css:ro

  bitwarden:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden.middlewares=redirectscheme
      - traefik.http.routers.bitwarden.rule=Host(`bitwarden.mcleut.stack`)
      - traefik.http.routers.bitwarden_secure.rule=Host(`bitwarden.mcleut.stack`)
      - traefik.http.services.bitwarden.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden_secure.tls.options=mintls13@file
    image: bitwardenrs/server:latest
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro 
    - /production/bitwarden_data:/data

  caddy:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.caddy.middlewares=redirectscheme
      - traefik.http.routers.caddy.rule=Host(`mcleut.stack`)
      - traefik.http.routers.caddy_secure.rule=Host(`mcleut.stack`)      
      - traefik.http.services.caddy.loadbalancer.server.port=80
      - traefik.http.routers.caddy_secure.tls.options=mintls13@file
    image: caddy:latest    
    volumes:
    - /production/caddy_data:/data
    - /production/me:/usr/share/caddy:ro

  cloudtorrent:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.cloudtorrent.middlewares=redirectscheme
      - traefik.http.routers.cloudtorrent.rule=Host(`torrent.mcleut.stack`)
      - traefik.http.routers.cloudtorrent_secure.rule=Host(`torrent.mcleut.stack`)
      - traefik.http.services.cloudtorrent.loadbalancer.server.port=3000
      - traefik.http.routers.cloudtorrent_secure.tls.options=mintls13@file
    image: jpillora/cloud-torrent:latest
    volumes:
    - /production/cloudtorrent_data:/downloads

  codimd:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.codimd.middlewares=redirectscheme
      - traefik.http.routers.codimd.rule=Host(`codimd.mcleut.stack`)
      - traefik.http.routers.codimd_secure.rule=Host(`codimd.mcleut.stack`)
      - traefik.http.services.codimd.loadbalancer.server.port=3000
      - traefik.http.routers.codimd_secure.tls.options=mintls13@file
    image: linuxserver/codimd:latest
    volumes:
    - /production/codimd_data:/config
    - /etc/localtime:/etc/localtime:ro

  fail2ban:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.tcp.routers.fail2ban.middlewares=redirectscheme
    cap_add:
      - NET_ADMIN
      - NET_RAW  
    image: crazymax/fail2ban:latest
    volumes:
    - /var/log:/var/log:ro
    - /production/fail2ban_data:/data

  gitea:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.middlewares=redirectscheme
      - traefik.http.routers.gitea.rule=Host(`git.mcleut.stack`)
      - traefik.http.routers.gitea_secure.rule=Host(`git.mcleut.stack`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.routers.gitea_secure.tls.options=mintls13@file
    image: gitea/gitea:latest
    volumes:
    - /production/gitea_data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  
  nextcloud:
    env_file: ./nextcloud.env
    image: arm32v7/nextcloud:20.0.6-fpm-alpine
    secrets:
    - nextcloud_admin-password
    - nextcloud_admin-user
    volumes:
    - /production/nextcloud_data:/var/www/html

  nextcloud_nginx:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_calendar.redirectregex.regex=.*
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_calendar.redirectregex.replacement=https://nextcloud.mcleut.stack/apps/calendar/
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_contacts.redirectregex.regex=.*
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_contacts.redirectregex.replacement=https://nextcloud.mcleut.stack/apps/contacts/
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_office.redirectregex.regex=.*
      - traefik.http.middlewares.nextcloud_nginx_secure_redirectregex_office.redirectregex.replacement=https://nextcloud.mcleut.stack/apps/collabora/
      - traefik.http.routers.nextcloud_nginx.middlewares=redirectscheme
      - traefik.http.routers.nextcloud_nginx.rule=Host(`nextcloud.mcleut.stack`)
      - traefik.http.routers.nextcloud_nginx_secure.rule=Host(`nextcloud.mcleut.stack`)
      - traefik.http.routers.nextcloud_nginx_secure_calendar.middlewares=nextcloud_nginx_secure_redirectregex_calendar@docker
      - traefik.http.routers.nextcloud_nginx_secure_calendar.rule=Host(`calendar.mcleut.stack`)
      - traefik.http.routers.nextcloud_nginx_secure_contacts.middlewares=nextcloud_nginx_secure_redirectregex_contacts@docker
      - traefik.http.routers.nextcloud_nginx_secure_contacts.rule=Host(`contacts.mcleut.stack`)
      - traefik.http.routers.nextcloud_nginx_secure_office.middlewares=nextcloud_nginx_secure_redirectregex_office@docker
      - traefik.http.routers.nextcloud_nginx_secure_office.rule=Host(`office.mcleut.stack`)
      - traefik.http.services.nextcloud_nginx.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
    image: nginx:1.19.6-alpine
    volumes:
    - /production/nextcloud-nginx.conf:/etc/nginx/nginx.conf
    - /production/nextcloud_data:/var/www/html/

 # pihole:
 #   deploy:
 #     labels:
 #     - traefik.enable=true
 #     - traefik.http.routers.pihole.middlewares=redirectscheme
 #     - traefik.http.routers.pihole.rule=Host(`pihole.mcleut.stack`)
 #     - traefik.http.routers.pihole.rule=Host(`pihole.mcleut.stack`) && PathPrefix(`/admin`)
 #     - traefik.http.routers.pihole_secure.rule=Host(`pihole.mcleut.stack`)
 #     - traefik.http.services.pihole.loadbalancer.server.port=80
 #     - traefik.http.routers.pihole_secure.tls.certresolver=default
 #   image: pihole/pihole:latest
 #   ports:
 #     - 53:53
 #   environment:
 #     TZ: 'Europe/Berlin'
 #     ServerIP: 192.168.0.212
 #   volumes:
 #   - /production/pihole_data/:/etc/pihole/
 #   - /production/dnsmasq_data/:/etc/dnsmasq.d/
 #   - /etc/localtime:/etc/localtime:ro
 #   - /etc/timezone:/etc/timezone:ro
 #   cap_add:
 #   - NET_ADMIN
  
  pad:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.pad.middlewares=redirectscheme
      - traefik.http.routers.pad.rule=Host(`pad.mcleut.stack`)
      - traefik.http.routers.pad_secure.rule=Host(`pad.mcleut.stack`)
      - traefik.http.services.pad.loadbalancer.server.port=9001
      - traefik.http.routers.pad_secure.tls.options=mintls13@file
    image: etherpad/etherpad:latest
    volumes:
    - /production/pad_data:/data 

  portainer:
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password-file '/run/secrets/portainer_admin-password'
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.middlewares=redirectscheme
      - traefik.http.routers.portainer.rule=Host(`portainer.mcleut.stack`)
      - traefik.http.routers.portainer_secure.rule=Host(`portainer.mcleut.stack`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer_secure.tls.options=mintls13@file
      mode: replicated
      placement:
        constraints:
        - node.role == manager
      replicas: 1
    image: portainer/portainer:latest
    secrets:
    - portainer_admin-password
    volumes:
    - /production/portainer_data:/data

  portainer-agent:
    deploy:
      mode: global
      placement:
        constraints:
        - node.platform.os == linux
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    image: portainer/agent:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker/volumes:/var/lib/docker/volumes

  resilio:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.resilio.middlewares=redirectscheme
      - traefik.http.routers.resilio.rule=Host(`resilio.mcleut.stack`)
      - traefik.http.routers.resilio_secure.rule=Host(`resilio.mcleut.stack`)
      - traefik.http.services.resilio.loadbalancer.server.port=8888
      - traefik.http.routers.resilio_secure.tls.options=mintls13@file
    image: resilio/sync:latest 
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /production/resilio_data:/sync
    
  torproxy:
    deploy:
      labels:
      - traefik.enable=true
    image: dperson/torproxy:armhf
    ports:
    - 8080:8080
    - 9050:9050
    environment:
      TZ: 'Europe/Berlin'
    volumes:
    - /production/torproxy_data/torrc:/etc/tor/torrc 

  traefik:
    command:
    - --api=true
    - --entryPoints.web.address=:80
    - --entryPoints.web-secure.address=:443
    - --providers.docker=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.exposedByDefault=false
    - --providers.docker.swarmMode=true
    - --providers.file.filename=/dynamic.yml
    - --providers.file.watch=true
    - --pilot.token=111fb60c-3bfd-47b3-85a3-4886c77a7018
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.middlewares.header_cors.headers.accessControlAllowHeaders=authorization,content-type
      - traefik.http.middlewares.header_cors.headers.accessControlAllowOrigin=*
      - traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=redirectscheme
      - traefik.http.routers.traefik.rule=Host(`traefik.mcleut.stack`)
      - traefik.http.routers.traefik_secure.rule=Host(`traefik.mcleut.stack`)
      - traefik.http.routers.traefik_secure.service=api@internal
      - traefik.http.routers.traefik_secure.tls.options=mintls13@file    
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      mode: global
      placement:
        constraints:
        - node.role == manager
    image: traefik:latest
    ports:
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./certificates/:/etc/traefik/acme/
    - ./traefik_data/dynamic.yml:/dynamic.yml:ro

version: "3.7"
volumes:
  acme_data: {}
  bitwarden_data: {}
  caddy_data: {}
  cloudtorrent_data: {}
  codimd_data: {}
  fail2ban_data: {}
  gitea_data: {}
  nextcloud_data: {}
  pad_data: {}
  portainer_data: {}
  pihole_data: {}
  resilio_data: {}
  torproxy_data: {}
  traefik_data: {}

